services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gearsan
      POSTGRES_PASSWORD: devpool2567
      POSTGRES_DB: workflowdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: